services:
  # SQL Server with automatic Sakila database setup
  sqlserver:
    build: .
    container_name: msgdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@1
      - MSSQL_PID=Developer
    ports:
      - "${SQL_PORT:-1433}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Password@1' -C -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

volumes:
  sqlserver_data:
    driver: local